# Generated by Django 3.1.7 on 2021-04-24 08:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=30)),
                ('artist', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('year', models.IntegerField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('likedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.student')),
            ],
        ),
    ]
