# Generated by Django 3.1.7 on 2021-04-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
