# Generated by Django 3.1.7 on 2021-04-25 01:03

from django.db import migrations, models
import musics.models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_song_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='likedBy',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=musics.models.Student),
        ),
    ]
